# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: PII Inventory
email: gsa.privacyact@gsa.gov
description: >- # this means to ignore newlines until "baseurl:"
  This dashboard presents information about personally identifiable information (PII) that is collected by GSA systems.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://example.gov" # the base hostname & protocol for your site, e.g. http://example.com

# Twitter handle. Only the handle, not the URL.
twitter: 18F

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-????????-??

# Configuration for DAP, add your agency ID here:
dap_agency: GSA

# Site Navigation
# primary_navigation:
  # - name: Old Prototypes
  #   url: /old-prototypes
  # - name: Table Layout
  #   url: /table-layout

# secondary_navigation:
#   - name: Secondary link
#     url: "#main-content"
#   - name: Another secondary link
#     url: "#main-content"

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  endpoint: https://search.usa.gov # You should not change this.
  affiliate: federalist-uswds-example # replace this with your search.gov account
  access_key: xX1gtb2RcnLbIYkHAcB6IaTRr4ZfN-p16ofcyUebeko= # This is placeholder. Not private.
  inline: true #this renders the results on the same domain. Otherwise, it will render the results in the search.gov domain

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty

sass:
  sass_dir: assets/

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - CONTRIBUTING.md
  - LICENSE.md
  - assets
  - google_scripts
  - GS_GH_notes.md
  - spec

assets:
  sources:
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss

defaults:
  -
    scope:
      path: ""
    values:
      excerpt: "WAT"
